### PR TITLE
Ensure encoding whitespace separators are consumed (Issue 22)

### LINKED ISSUE #22: erroneous subject field parsing (and possibly other fields to?)
raw email:
```
Subject: =?utf-8?B?QVc6IEdyb8OfZSBHZWJ1cnRzdGFncy1QYXJ0eSBpbSBN?=
	=?utf-8?B?YWkgKGljaCBmZWllcmUgbmFjaHRyw6RnbGljaCkh?=
```
Output:
`AW: Große Geburtstags-Party im M ai (ich feiere nachträglich)!`

Should Be: 
`AW: Große Geburtstags-Party im Mai (ich feiere nachträglich)!`

the field "threadTopic" shows the space at a different place int he text, so it is also affected.

### PR DESCRIPTION
**Pull request by brettz9**
~Builds on #24, #25, #26, #27, and #28.~

- fix: ensure linear whitespace separators of encoded-words are consumed within "Subject" headers and are not displayed (fixes #22)
- test: rename `issue-22` testing file to `issues` as contains other issues

in "Use of encoded-words in message headers" of https://tools.ietf.org/html/rfc1342:

> An encoded-word may replace a "text" token (as defined by RFC 822) in:
>  (1) a Subject or Comments header field

Per elsewhere in the document an `encoded-word` is defined as:

```ebnf
encoded-word = "=" "?" charset "?" encoding "?" encoded-text "?" "="
```

The "MESSAGE SPECIFICATION" "Syntax" section at https://tools.ietf.org/html/rfc822#section-4.1 indicates the following rules of interest which originally defined a message header (and which the above non-ASCII spec modifies through allowing certain fields like the subject header to use `encoded-word`):

```ebnf
- message     =  fields *( CRLF *text )
- fields      =    dates                      ; Creation time,
                      source                     ;  author id & one
                    1*destination                ;  address required
                     *optional-field             ;  others optional
optional-field =
                 /  "Message-ID"        ":"   msg-id
                 /  "Resent-Message-ID" ":"   msg-id
                 /  "In-Reply-To"       ":"  *(phrase / msg-id)
                 /  "References"        ":"  *(phrase / msg-id)
                 /  "Keywords"          ":"  #phrase
                 /  "Subject"           ":"  *text
                 /  "Comments"          ":"  *text
                 /  "Encrypted"         ":" 1#2word
                 /  extension-field              ; To be defined
                 /  user-defined-field           ; May be pre-empted
```

...noting that "Subject" is followed by multiple `text`, where `text` is the token that an "encoded-word may replace".

And also per "Use of encoded-words in message headers",

> An encoded-word must be
>    separated from an adjacent encoded-word, "word", "text", "ctext", or
>    "special" by a linear white-space character or a newline.  When
>    displaying a particular header field" (in the RFC 822 sense)
>    containing one or more encoded-words, an unencoded SPACE character
>    that immediately follows the encoded-word is not displayed.  A
>    newline that immediately follows an encoded-word is not displayed
>    unless the encoded-word is the last token in that "field". 

...where the relevant rules from RFC822 are:

```ebnf
linear-white-space =  1*([CRLF] LWSP-char)  ; semantics = SPACE
                                                 ; CRLF => folding
LWSP-char   =  SPACE / HTAB                 ; semantics = SPACE
                                            ; (  Octal, Decimal.)
SPACE       =  <ASCII SP, space>            ; (     40,      32.)
HTAB        =  <ASCII HT, horizontal-tab>   ; (     11,       9.)
```

So in this PR I just consume any extra `linear-white-space`, i.e., tab or space (there may be none), causing the #22 test to pass.

## Some additional info that may help with such encoding in other fields

FWIW, note that the spec also speaks to other fields where, as per the above, the space separators are "not displayed" (where separators should be consumed), e.g.,

> As a replacement for a "word" entity within a "phrase", for example,
>  one that precedes an address in a From, To, or Cc header.  The EBNF
>  definition for phrase from RFC 822 thus becomes:
>
>  phrase = 1*(encoded-word / word)

One would have to follow the `from`, `to`, etc. code mapping leading to `Contact.parse` in your `header.js` code (which also uses the `qp.decodeWord` method to which I have added an argument) in order to find out if and where such encoding would need similar fixing (e.g., through use of the argument I have added to `qp.decodeWord`), but the rules appear more complex, and I haven't investigated them with this PR. (A proper investigation may in any case help with #23 , though I am preoccupied with other work but thought I could offer this PR at least).

### CODE REVIEW

**Comment by brettz9** [comment]
This has now been amended and rebased so it is no longer dependent on the other PRs.

**Comment by brettz9** [comment]
Note that this only failing Travis as it was already failing. It now only has 3 errors instead of 4.

**Comment by jhermsmeier** [comment]
Sorry it's taken me a while to get back to this – regarding your reference to the specifications; as I mentioned on the other issue this module wasn't really intended to be spec compliant, but just work well enough on after-the-fact emails. Now that I've decided to eventually turn this into a spec-compliant encoder/decoder that'll change. Many thanks for already taking the time to wade through the RFCs!

**Comment by jhermsmeier** [comment]
Published in `envelope@2.1.0`

**Pull request merged**
