### PR TITLE
Eslint

### PR DESCRIPTION
**Pull request by brettz9**
Builds on #24 and #25 .

chore: add `eslint` with npm script and `eslint:recommended` config and apply

### CODE REVIEW

**Comment by jhermsmeier** [comment]
Thanks! While I appreciate the PR, I have to politely decline, as I've never seen much value come out of formatting JavaScript linters, and I'm generally opposed to adding dependencies that aren't necessary.

**Comment by brettz9** [comment]
If your concern is with restrictive formatting, the rules applied in the `eslint:recommended` config I have used are I think not supposed to be purely stylistic concerns but are those which are the likely or potential source of bugs.

For example, in the changes called for in the attached config, which though not bugs in this case, are meant to warn if there was an assignment which was intended to be a comparison (wrapping in parenthesis is meant as a convention to suggest this was intended). The other changes are to avoid unused variables, since these can sometimes be due to misspelled variable names. And eslint allows disabling rules one doesn't like.

I know I've caught countless bugs in my own code and in others' code, and I think its presence brings assurances to those looking at a project that it is free of some obvious problems, even if it's developers don't tend to make such mistakes.

However, unless hearing back (no need to reply), I'll assume that you're not convinced, and I guess will just look to apply my own global config to ensure I don't introduce other mistakes during my development. Thanks!

**Comment by brettz9** [comment]
I've rebased in case your reopening meant you were open to adding it.

**Comment by jhermsmeier** [comment]
> in case your reopening meant you were open to adding it.

Yeah, thanks! I'm willing to give it a shot, after all we can remove it again should it get in the way.

**Comment by brettz9** [comment]
Sure--and if you end up liking the linting, but find any particular rules annoying, feel free to let me know as we can disable those rules or change their configuration.

**Pull request merged**
