### PR TITLE
Npm

### PR DESCRIPTION
**Pull request by brettz9**
Builds on #24, #25, #26, #27.

- npm: Update dep. iconv-lite and devDep. mocha

### CODE REVIEW

**Comment by jhermsmeier** [comment]
I don't think this PR needs to depend on the other PRs – just updating `iconv-lite` should suffice, I think. Mocha is actually intentionally not updated past v5.x, because the following versions of it have had an explosion of unnecessary dependencies that I'd like to do without. And I should note that I'm planning to replace Mocha with something else entirely soon.

**Comment by brettz9** [comment]
Re: Mocha, ok, sure. (This is where such a case where one could use a `.ncurc` to avoid `npm-check-updates` updating (when running its update command)!)

Out of curiosity, do you have a specific testing library in mind? I'm a fan of certain Mocha features (which I know other libraries have):

1. Has `.only()` to selectively run certain tests; very helpful in rapid development
2. It works well with nyc
3. Has some color for quick feedback (and pleasantness)
4. Its syntax and behavior is well-familiar.

But I know there are other libraries, and perhaps another libraries meets some particular needs you have in mind for the project.

**Comment by jhermsmeier** [comment]
> Out of curiosity, do you have a specific testing library in mind? [...]

I've started writing my own test harness, inspired by the reasoning behind [@volument/baretest](https://github.com/volument/baretest) – I've long had my qualms about the growing dependency trees of popular test frameworks, and unfortunately `baretest` doesn't quite do all I'd like either.

> But I know there are other libraries, and perhaps another libraries meets some particular needs you have in mind for the project.

Thinking about it though, it might make sense to keep Mocha around on this one, as `nyc` integration is now a stopper on that.

**Comment by brettz9** [comment]
Ok, I've updated to only make a minor update for Mocha as well as to iconv-lite.

While I'm happy to remove this file if you like, I went ahead and added the `.ncurc.js` file in case I happen to be developing on this later and use [`npm-check-updates`](https://github.com/tjunnone/npm-check-updates) to try to update deps again, so I don't accidentally annoy you with a PR to update Mocha again, forgetting you wanted to peg it at version 5. :)

**Pull request merged**
